name: NapSspIOSSample
options:
  bundleIdPrefix: com.nasmedia
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "15.0"

packages:
  AdMixer:
    path: Vendor/Packages/AdMixer
  AdMixerMediation:
    path: Vendor/Packages/AdMixerMediation
  AdMixerMediationGAM:
    path: Vendor/Packages/AdMixerMediationGAM
  AdMixerMediationAdFit:
    path: Vendor/Packages/AdMixerMediationAdFit

targets:
  NapSspIOSSample:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/NapSspIOSSample
    dependencies:
      - package: AdMixer
      - package: AdMixerMediation
      - package: AdMixerMediationGAM
      - package: AdMixerMediationAdFit
    settings:
      base:
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.nasmedia.NapSspIOSSample
        XCCONFIG_FILE: Config.xcconfig
        INFOPLIST_KEY_NSUserTrackingUsageDescription: "맞춤형 광고 제공을 위해 기기 식별자를 사용합니다."
        INFOPLIST_KEY_GADApplicationIdentifier: "ca-app-pub-3839806749171044~7545408326"
      configs:
        Debug:
          XCCONFIG_FILE: Config.xcconfig
        Release:
          XCCONFIG_FILE: Config.xcconfig
    configFiles:
      Debug: Config.xcconfig
      Release: Config.xcconfig
